spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

  properties:
    hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true
    default_schema: public
    jdbc.lob.non_contextual_creation: true

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: password
  driver-class-name: org.postgresql.Driver